# .readthedocs.yaml
# Read the Docs configuration file for SPINE
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation with MkDocs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install the project in editable mode
      - pip install --upgrade pip setuptools wheel
    post_install:
      - pip install -e .

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub

# Python configuration
python:
  install:
    - requirements: docs/requirements_rtd.txt
    - method: pip
      path: .
