base:
  iterations: -1
  unwrap: true
  overwrite_log: true

io:
  loader:
    minibatch_size: 2
    shuffle: False
    num_workers: 4
    collate_fn: all
    sampler: sequential
    dataset:
      provider: larcv
      file_keys: null
      schema:
        input_data:
          provider: sparse3d
          sparse_event: sparse3d_pcluster
        seg_label:
          provider: sparse3d
          sparse_event: sparse3d_pcluster_semantics
        clust_label:
          provider: cluster3d
          cluster_event: cluster3d_pcluster
          sparse_value_event: sparse3d_pcluster
          sparse_semantics_event: sparse3d_pcluster_semantics
          clean_data: true
          particle_info:
            particle_event: particle_pcluster
        ppn_label:
          provider: particle_points
          particle_event: particle_pcluster
          sparse_event: sparse3d_pcluster
          include_point_tagging: true
        coord_label:
          provider: particle_coords
          particle_event: particle_pcluster
          sparse_event: sparse3d_pcluster
        graph_label:
          provider: particle_graph
          particle_event: particle_pcluster
          cluster_event: cluster3d_pcluster
        particles:
          provider: particle
          particle_event: particle_pcluster
          cluster_event: cluster3d_pcluster
        meta:
          provider: meta
          sparse_event: sparse3d_pcluster
        run_info:
          provider: run_info
          sparse_event: sparse3d_pcluster
  writer:
    provider: hdf5
    file_name: null
    overwrite: true
    append: false
