"""Reusable policies for combining heterogeneous training objectives."""

from __future__ import annotations

import math
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

import torch

__all__ = ["LossBalancer", "LossTerm"]


@dataclass(frozen=True)
class LossTerm:
    """One scalar objective and the likelihood family that produced it.

    The producer owns ``family`` and ``scale``. Users select a balancing
    policy and may optionally express task priorities, but should not have to
    repeat facts already known by the loss implementation.

    Attributes
    ----------
    value : torch.Tensor
        Scalar differentiable objective.
    family : {"categorical", "gaussian", "laplace", "composite"}
        Likelihood family used by uncertainty balancing.
    active : bool, default True
        Whether the current batch contains supervision for this objective.
    scale : float, default 1.0
        Producer-owned priority multiplying the complete balanced term.
    """

    value: torch.Tensor
    family: str
    active: bool = True
    scale: float = 1.0


class LossBalancer(torch.nn.Module):
    """Combine a fixed, producer-declared collection of scalar objectives.

    The loss producer declares each objective's likelihood family once, while
    configuration selects how those objectives are combined. ``sum`` and
    ``fixed`` introduce no trainable state. ``uncertainty`` learns one log
    variance per objective and applies the likelihood-appropriate form of
    homoscedastic uncertainty weighting.

    Producer scales and optional user weights are treated as explicit task
    priorities. They multiply the complete balanced term, including its
    regularizer, so learned uncertainty cannot absorb an intentional priority.
    Objectives without supervision in the current batch contribute neither a
    data term nor a regularizer.

    Notes
    -----
    With ``s = log(sigma**2)``, categorical objectives contribute
    ``exp(-s) * L + s / 2`` and Gaussian objectives contribute
    ``exp(-s) * L / 2 + s / 2``. Gaussian variables start at ``-log(2)`` so
    every objective initially has unit effective weight. A producer may label
    an already-combined stage objective as ``composite``; its generic learned
    scale contributes ``exp(-s) * L + s`` without pretending the aggregate is
    generated by one likelihood family.
    """

    _FAMILIES = {"categorical", "gaussian", "laplace", "composite"}

    def __init__(
        self,
        families: Mapping[str, str],
        config: Mapping[str, Any] | None = None,
    ) -> None:
        """Initialize the balancing policy and any learned task variables.

        Parameters
        ----------
        families : mapping of str to str
            Stable objective names and their producer-declared likelihood
            families.
        config : mapping, optional
            Policy configuration. ``name`` selects ``sum``, ``fixed`` or
            ``uncertainty``; optional ``weights`` specify user priorities by
            objective name. Omitted configuration is equivalent to
            ``{"name": "sum"}``.

        Raises
        ------
        TypeError
            If weights or policy options are malformed.
        ValueError
            If the policy, task names, weights or likelihood families are
            invalid.
        """
        super().__init__()
        if not families:
            raise ValueError("Loss balancing requires at least one objective.")

        if config is not None and not isinstance(config, Mapping):
            raise TypeError("Loss-balancing configuration must be a mapping.")
        settings = {} if config is None else dict(config)
        self.mode = str(settings.pop("name", "sum")).lower()
        if self.mode not in {"sum", "fixed", "uncertainty"}:
            raise ValueError(
                "Loss balancing `name` must be 'sum', 'fixed' or 'uncertainty'."
            )

        priorities = settings.pop("weights", {})
        if not isinstance(priorities, Mapping):
            raise TypeError("Loss balancing `weights` must be a mapping.")
        if settings:
            unexpected = ", ".join(sorted(settings))
            raise TypeError(f"Unexpected loss-balancing options: {unexpected}.")

        self.families = dict(families)
        unknown_priorities = set(priorities) - set(self.families)
        if unknown_priorities:
            names = ", ".join(sorted(unknown_priorities))
            raise ValueError(f"Unknown loss-balancing objectives: {names}.")
        self.priorities = {
            name: float(priorities.get(name, 1.0)) for name in self.families
        }
        for name, weight in self.priorities.items():
            if not math.isfinite(weight) or weight < 0.0:
                raise ValueError(
                    f"Loss-balancing weight for `{name}` must be finite and "
                    "nonnegative."
                )

        self.log_variances = torch.nn.ParameterDict()
        if self.mode == "uncertainty":
            unsupported = {
                name: family
                for name, family in self.families.items()
                if family not in self._FAMILIES
            }
            if unsupported:
                details = ", ".join(
                    f"{name}={family}" for name, family in sorted(unsupported.items())
                )
                raise ValueError(
                    "Uncertainty balancing does not support these objective "
                    f"families: {details}."
                )
            for name, family in self.families.items():
                # Gaussian NLL has a one-half data coefficient. Starting at
                # -log(2) makes its effective coefficient one, like every
                # other term, while retaining the likelihood-derived formula.
                initial = -math.log(2.0) if family == "gaussian" else 0.0
                self.log_variances[name] = torch.nn.Parameter(torch.tensor(initial))

    def forward(
        self, terms: Mapping[str, LossTerm]
    ) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
        """Combine objective terms and return scalar diagnostics.

        This preserves the ordinary two-value module interface. Training
        systems which also need the differentiable per-objective contributions
        should call :meth:`combine`.

        Parameters
        ----------
        terms : mapping of str to LossTerm
            Current scalar value, activity and producer scale for every
            objective declared at construction.

        Returns
        -------
        torch.Tensor
            Combined differentiable objective.
        dict
            Detached effective weights and contribution diagnostics.
        """
        total, diagnostics, _ = self.combine(terms)
        return total, diagnostics

    def combine(self, terms: Mapping[str, LossTerm]) -> tuple[
        torch.Tensor,
        dict[str, torch.Tensor],
        dict[str, LossTerm],
    ]:
        """Combine objectives and retain their weighted contributions.

        Parameters
        ----------
        terms : mapping of str to LossTerm
            Current scalar value, activity and producer scale for every
            objective declared at construction.

        Returns
        -------
        torch.Tensor
            Combined differentiable objective.
        dict
            Detached effective weights, contributions, activity indicators
            and, for uncertainty balancing, learned log variances. Diagnostic
            keys use the forms ``<name>_weight``, ``<name>_weighted_loss``,
            ``<name>_active`` and ``<name>_log_variance``.
        dict
            Differentiable contribution of every objective after producer
            scales, user priorities, uncertainty coefficients and activity
            masking. These terms sum exactly to the combined objective and are
            suitable for task-gradient methods such as PCGrad.

        Raises
        ------
        TypeError
            If an objective value is not a scalar tensor.
        ValueError
            If objective names, families or scales do not match the declared
            collection.
        """
        if set(terms) != set(self.families):
            missing = sorted(set(self.families) - set(terms))
            extra = sorted(set(terms) - set(self.families))
            raise ValueError(
                "Loss terms do not match the configured objectives; "
                f"missing={missing}, extra={extra}."
            )

        total: torch.Tensor | None = None
        diagnostics: dict[str, torch.Tensor] = {}
        balanced_terms: dict[str, LossTerm] = {}
        for name, family in self.families.items():
            term = terms[name]
            if term.family != family:
                raise ValueError(
                    f"Objective `{name}` declared family `{term.family}`, "
                    f"expected `{family}`."
                )
            if not isinstance(term.value, torch.Tensor) or term.value.numel() != 1:
                raise TypeError(f"Objective `{name}` must be a scalar tensor.")
            if not math.isfinite(term.scale) or term.scale < 0.0:
                raise ValueError(
                    f"Objective scale for `{name}` must be finite and nonnegative."
                )

            # Combine the producer's native scale with any user-level priority.
            priority = term.scale * self.priorities[name]
            active = bool(term.active) and priority > 0.0
            coefficient = term.value.new_tensor(priority)
            contribution = term.value * priority

            # Select the negative-log-likelihood form from producer metadata.
            if self.mode == "uncertainty":
                log_variance = self.log_variances[name]
                if family == "categorical":
                    data_factor = torch.exp(-log_variance)
                    regularizer = 0.5 * log_variance
                    offset = 0.0
                elif family == "gaussian":
                    data_factor = 0.5 * torch.exp(-log_variance)
                    regularizer = 0.5 * log_variance
                    # Center the additive constant so the initial contribution
                    # equals the historical unweighted data term.
                    offset = 0.5 * math.log(2.0)
                elif family == "laplace":
                    data_factor = torch.exp(-0.5 * log_variance)
                    regularizer = 0.5 * log_variance
                    offset = 0.0
                else:  # Generic learned scale for an already-combined stage.
                    data_factor = torch.exp(-log_variance)
                    regularizer = log_variance
                    offset = 0.0
                coefficient = data_factor.detach() * priority
                contribution = priority * (
                    data_factor * term.value + regularizer + offset
                )
                diagnostics[f"{name}_log_variance"] = log_variance.detach()

            if not active:
                contribution = term.value * 0.0
                if self.mode == "uncertainty":
                    # Keep every learned variable in the autograd graph so a
                    # conditionally absent task is safe under DDP without
                    # allowing its regularizer to update.
                    contribution = contribution + self.log_variances[name] * 0.0
                coefficient = coefficient * 0.0

            total = contribution if total is None else total + contribution
            balanced_terms[name] = LossTerm(
                contribution,
                family,
                active=active,
            )
            diagnostics[f"{name}_weight"] = coefficient.detach()
            diagnostics[f"{name}_weighted_loss"] = contribution.detach()
            diagnostics[f"{name}_active"] = term.value.new_tensor(float(active))

        assert total is not None
        return total, diagnostics, balanced_terms
